config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show] do
    resources :locations, only: [:index, :show, :create, :update, :destroy] do
      resources :days, only: [:show], defaults: {format: :json}
    end
    get 'current_location/current_day' => 'days#current_day'  
    post 'locations/post_update' => 'locations#post_update', as: :locations_post_update
  end

  root 'guests_pages#index'
  get 'contact' => 'guests_pages#contact'
  post 'contact/send' => 'contacts#send_message'

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user 
  has_many :days
  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.address = geo.address
      obj.city    = geo.city
      obj.country = geo.country_code
    end
  end
  after_validation :reverse_geocode, if: ->(obj){ obj.latitude.present? and obj.longitude.present? }
  after_commit :transaction_success
  after_rollback :transaction_failed

  def set_current_location new_current_location
    previous_current_location = self
    previous_current_location.current_location = false
    new_current_location.current_location = true
    Location.transaction do
      previous_current_location.save!
      new_current_location.save!
    end
    new_current_location
  end

  def offset
    # Includes both offset from utc and daylight savings time offset
    iana_timezone = self.timezone
    ActiveSupport::TimeZone[iana_timezone].tzinfo.current_period.utc_total_offset / 3600.0
  end

  def self.update_day_for_user user
    location = user.current_location
    day = location.days.create new_day
    SpaWorker.perform_async day.id
  end

  def self.update_days
    new_day = self.new_day
    self.where( current_location: true
              ).find_each do |location|
                if location.offset == new_day[:offset]
                  day = location.days.create new_day
                  SpaWorker.perform_async day.id
                end
              end
  end

  def self.new_day
    current_time = DateTime.current

    # 15:15 becomes 15.25
    fractional_utc_time = current_time.hour
    fractional_utc_time += ((current_time.minute) / 15) * 0.25

    if fractional_utc_time <= 12
      # for regions West of London
      offset = -1 * fractional_utc_time
      new_day_time = current_time
    else
      # for regions Est of London
      offset = 24 - fractional_utc_time
      new_day_time = current_time.next_day
    end
    {
      offset: offset,
      day: new_day_time.day,
      month: new_day_time.month,
      year: new_day_time.year
    }
  end

  private
    def transaction_success
      logger.info "Current Location Update succeed for Location #{self.to_param}"
    end

    def transaction_failed
      logger.warn "Current Location Update failed for Location #{self.to_param}"
    end  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :locations

  def current_location
    self.locations.find_by current_location: true
  end

  def locations_for page
    locations.paginate(page: page, :per_page => 5).order("created_at DESC")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path current_user
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def send_message
    sender = params[:email]
    message = params[:message]
    ContactMailer.send_email(sender, message).deliver_later
    flash[:notice] = "Message sent successfully!"
    redirect_to contact_path
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_resource!

  def show
    @day = Day.find(params[:id])
    respond_to do |format|
      format.json {render json: @day }
    end
  end

  def current_day
    @day = current_user.current_location.days.last
    respond_to do |format|
      format.json {render json: @day }
    end
  end

  private

    def authorize_resource!      
      if !params[:user_id]
        redirect_to user_path current_user
        flash[:alert] = "You are not allowed to access another user's data!"
      elsif current_user.id != params[:user_id].to_i
        redirect_to user_path current_user
        flash[:alert] = "You are not allowed to access another user's data!"
      end    
    end
end

app/controllers/guests_pages_controller.rb
class GuestsPagesController < ApplicationController
  def index
    if user_signed_in?
      redirect_to current_user
    end
  end  

  def contact
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  layout 'users'

  def index
    @locations = current_user.locations_for params[:page]
  end

  def create
    @new_location = current_user.locations.build location_params
    @new_location.save
    TimezoneWorker.perform_async @new_location.id
    unless current_user.current_location.id == @new_location.id
      current_user.current_location.set_current_location @new_location    
    end
    @day = @new_location.days.create day_params
    SpaWorker.perform_async(@day.id)
    @current_location = current_user.current_location
    @location = Location.new
    @location.user_id = current_user.id
    redirect_to root_path
    # respond_to do |format|
    #   format.js
    # end
  end

  def update
    @new_location = current_user.locations.find_by id: params[:id]
    @old_location = current_user.current_location
    current_user.current_location.set_current_location @new_location

    @day = @new_location.days.build day_params
    @day.offset = @new_location.offset
    @day.save

    SpaWorker.perform_async(@day.id)
    @old_location.current_location = false
    respond_to do |format|
      format.js
    end
  end

  def post_update
    @location = current_user.locations.build location_params
    @location.save
    TimezoneWorker.perform_async @location.id
    unless current_user.current_location.id == @location.id
      current_user.current_location.set_current_location @location    
    end
    @day = @location.days.create day_params
    SpaWorker.perform_async(@day.id)
    respond_to do |format|
      format.js
    end
  end

  def show
    @location = Location.where(user_id: current_user.id).first
    respond_to do |format|
      format.json {render json: @location }
    end
  end

  def destroy
    @location = current_user.locations.find_by id: params[:id]
    @location.destroy
    respond_to do |format|
      format.js
    end
  end

  private

    def location_params
      params.require(:location).permit(:longitude, :latitude, :current_location)
    end

    def day_params
      params.require(:date_time).permit(:year, :day, :month, :offset)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_resource!

  def show
    @current_location = current_user.current_location
    @location = Location.new
    @location.user_id = current_user.id
  end

  private

    def authorize_resource!      
      if !params[:id]
        redirect_to user_path current_user
        flash[:alert] = "You are not allowed to access another user's data!"
      elsif current_user.id != params[:id].to_i
        redirect_to user_path current_user
        flash[:alert] = "You are not allowed to access another user's data!"
      end    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/guests_pages_helper.rb
module GuestsPagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  def addition_date_for location
    "#{time_ago_in_words location.created_at} ago" 
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def page_classes
    "#{params[:controller]} #{params[:action]}"
  end
end

app/views/guests_pages/contact.html.erb
<div class="bg">
  <div class="bg-color">
    <div class="container content">
      <%= render partial: 'layouts/partials/flash' %>
      <div class="authorization-form col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
        <h3>We would love to hear from you!</h3>
        <%= form_tag(contact_send_path, method: "post") do %>
          <fieldset>
            <div class="field form-group">
              <%= label_tag :email, "Your Email", class: "control-label" %><br />
              <div class="">
                <%= email_field_tag :email, nil, autofocus: true, class: "form-control" %>
              </div>
            </div>
            <div class="field form-group">
              <%= label_tag :message, "Your Message", class: "control-label" %><br />
              <div class="">
                <%= text_area_tag :message, nil, autofocus: true, class: "form-control" %>
              </div>
            </div>
            <div class="actions">
              <%= submit_tag "Send Message", class: "btn btn-sand" %>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/guests_pages/index.html.erb
<div class="bg">
  <div class="bg-color home">
    <div class="container content">
      <%= render partial: 'layouts/partials/flash' %>
      <div class="row">
        <div class="sun clearfix">
          <div class="col-sm-12">
             <h1>DeeBooster</h1>
             <h3>The world's most advanced sunbathing tool</h3>
          </div>
          <div id="left-block" class="col-sm-6 text-center">
            <img class="img-responsive" src="<%= asset_path 'tab.png' %>" alt="tab"/>
          </div>
          <div id="right-block" class="col-sm-6">
            <div class="row">
              <div class="col-sm-offset-2 col-sm-8">
                <p class="alert-success"></p>
                <p class="alert-warning"></p>
                <h3>Join now and start producing vitamin D with your own body</h3>
                <form class="newsletter-signup" role="form">
                  <div class="input-group">
                    <span class="input-group-btn">
                      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default btn-sand btn-blue" %>
                    </span>
                    <span class="input-group-btn">
                      <%= link_to "Sign In", new_user_session_path, class: "btn btn-default btn-sand" %>
                    </span>
                  </div><!-- /input-group -->
                </form>
              </div>
            </div>
            <p class="followus"></p>
            <ul class="social-icon">
              <li><a href=""><i class="fa fa-camera-retro"></i></a></li>
              <li><a href=""><i class="fa fa-facebook"></i></a></li>
              <li><a href=""><i class="fa fa-twitter"></i></a></li>
              <li><a href=""><i class="fa fa-youtube-square"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>  
</div>
<div class="clearfix"></div>
<div class="content-section-b">
  <div class="container">
  <div class="row">
      <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
          <hr class="section-heading-spacer">
          <div class="clearfix"></div>
          <h2 class="section-heading">Simple and Seamless<br>No complex forms</h2>
          <p class="lead">You don't need complex devices that are hard to use.</p>
          <p class="lead">You don't need to manually fill forms fields.</p>
          <p class="lead">DeeBoost detects seamlessly your current time <i class="fa fa-calendar"></i> and geographic location <i class="fa fa-map-marker"></i>in order to find the best time intervals for Vitamin D production.</p>
      </div>
      <div class="col-lg-5 col-sm-pull-6  col-sm-6">
        <img class="img-responsive" src="<%= asset_path 'dog.png' %>" alt=""/>
      </div>
  </div>
  </div>
</div>
<div class="content-section-a">
  <div class="container">
  <div class="row">
      <div class="col-lg-5 col-sm-6">
          <hr class="section-heading-spacer">
          <div class="clearfix"></div>
          <h2 class="section-heading">Deeboost is available<br>on any device</h2>
          <p class="lead">DeeBoost's web interface is responsive. That means it is optimized for all screen sizes <i class="fa fa-desktop"></i> including smartphones <i class="fa fa-mobile"></i> and tablets <i class="fa fa-tablet"></i> .</p>
      </div>
      <div class="col-lg-5 col-lg-offset-2 col-sm-6">
        <img class="img-responsive" src="<%= asset_path 'phones.png' %>" alt=""/>
      </div>
  </div>
  </div>
</div>
<div class="content-section-b">
  <div class="container">
  <div class="row">
      <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
          <hr class="section-heading-spacer">
          <div class="clearfix"></div>
          <h2 class="section-heading">Manage multiple locations<br></h2>
          <p class="lead">If you travel you can save different locations in DeeBoost.</p>
          <p class="lead">You can switch between saved locations with one simple click  <i class="fa fa-hand-pointer-o"></i> to view the data for a specific location.</p>
      </div>
      <div class="col-lg-5 col-sm-pull-6  col-sm-6">
        <img class="img-responsive" src="<%= asset_path 'ipad.png' %>" alt=""/>
      </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: '/layouts/partials/head'%>
</head>
<body class="guests_pages">

<%= render partial: 'layouts/partials/navigation' %>
<%= yield %>
 

<%= render partial: '/layouts/partials/landing_js_footer' %>

</body>
</html>

app/views/layouts/partials/_flash.html.erb
<% if notice %>
    <p class="notice alert alert-success text-center"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-warning text-center"><%= alert if alert %></p>
<% end %>

app/views/layouts/partials/_head.html.erb
<meta charset="UTF-8">
<title>DeeBooster - Vitamin D boosting app</title>
<meta name="description" content="Using this app everyone can find the best time intervals when their body can produce Vitamin D in thier part of the world.">
<meta name="author" content="DeeBooster">
<meta name="authorUrl" content="http://www.DeeBooster.Com">
    
<!-- Mobile Specific Meta -->   
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<!-- Font Awesome -->
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">

<!-- Added google font -->
<link href='http://fonts.googleapis.com/css?family=Lato:400,700|Lobster|Roboto+Slab:400,700' rel='stylesheet' type='text/css'>

app/views/layouts/partials/_landing_js_footer.erb
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">⋅</li>
                        <li>
                            <%= link_to "Sign in", new_user_session_path %>
                        </li>
                        <li class="footer-menu-divider">⋅</li>
                        <li>
                            <%= link_to "Sign up", new_user_registration_path %>
                        </li>
                        <li class="footer-menu-divider">⋅</li>
                        <li>
                            <%= link_to "Contact", contact_path %>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright © DeeBoost 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    
    <%= javascript_include_tag "core/TimeCircles.js" %>
    <%= javascript_include_tag "core/jquery.ajaxchimp.min.js" %>
    <%= javascript_include_tag "core/script.js" %>
    <%= javascript_include_tag "core/jquery.placeholder.js" %>
    <script type="text/javascript">
      $(function() {
        // Invoke the plugin
        $('input, textarea').placeholder();
      });
    </script>
    <script>
      $("#count-down").TimeCircles(
       {   
           circle_bg_color: "#8a7f71",
           use_background: true,
           bg_width: 1.0,
           fg_width: 0.02,
           time: {
                Days: { color: "#fefeee" },
                Hours: { color: "#fefeee" },
                Minutes: { color: "#fefeee" },
                Seconds: { color: "#fefeee" }
            }
       }
    );

    </script>

app/views/layouts/partials/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><h1>DeeBooster</h1></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse" aria-expanded="true">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/partials/users/_head.html.erb
<meta charset="UTF-8">
<title>DeeBooster - Vitamin D boosting app</title>
<meta name="description" content="Using this app everyone can find the best time intervals when their body can produce Vitamin D in thier part of the world.">
<meta name="author" content="DeeBooster">
<meta name="authorUrl" content="http://www.DeeBooster.Com">
    
<!-- Mobile Specific Meta -->   
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
<%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track' => true %>
<!-- Google Charts -->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<%= javascript_include_tag 'users', 'data-turbolinks-track' => true %>

<%= csrf_meta_tags %>

<!-- Font Awesome -->
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">

<!-- Added google font -->
<link href='http://fonts.googleapis.com/css?family=Lato:400,700|Lobster|Roboto+Slab:400,700' rel='stylesheet' type='text/css'>

app/views/layouts/partials/users/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><h1>DeeBooster</h1></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse" aria-expanded="true">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Locations", user_locations_path(current_user) %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: '/layouts/partials/users/head'%>
</head>
<body class="users_pages">

<%= render partial: 'layouts/partials/users/navigation' %>

<div class="js-page <%= page_classes %>">
  <div class="padding-wrapper">
    <div class="container-fluid content">
      <%= render partial: 'layouts/partials/flash' %>
      <%= yield %>
    </div>
  </div>  
</div>  

<%= render partial: '/layouts/partials/users/footer' %>

</body>
</html>

app/views/locations/_current_location.html.erb
<div>
<div class="current-location-details">
  <table class="table table-striped current-location-table">
     <thead>
       <tr>
         <th>Current Address</th>
         <th>Addition Date</th>
         <th>Latitude</th>
         <th>Longitude</th>
       </tr>
     </thead>
     <tbody>
       <tr>
         <td><%= current_location.address %></td>
         <td><%= addition_date_for current_location %></td>
         <td><%= current_location.latitude %></td>
         <td><%= current_location.longitude %></td>
       </tr>
     </tbody>
  </table>
</div>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=760x400&sensor=false&zoom=13&markers=#{current_location.latitude}%2C#{current_location.longitude}", class: "current-location-map" %>
</div>

app/views/locations/_location.html.erb
<tr id="location_<%= location.id %>" class="<%= 'current_location' if location.current_location? %>">
  <td><%= addition_date_for location %></td>
  <td><%= location.latitude %></td>
  <td><%= location.longitude %></td>
  <td class="delete_location">
  <%= link_to raw("<i class='glyphicon glyphicon-remove' style=''></i><b>Delete Location</b>"), user_location_path(current_user, location), method: :delete, class: "btn btn-danger", remote: true  %>
  </td>
  <td><%= render partial: "location_form", locals: { location: location } %> </td>
</tr>

app/views/locations/_location_form.html.erb
<% if location.current_location? %>
  <div class="btn btn-success">
    <i class="glyphicon glyphicon-map-marker"></i>
    <b>Current Location</b>
  </div>
<% else %>
  <%= form_for [current_user, location], remote: true do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :longitude %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :current_location, value: true %>
    <%= hidden_field :date_time, :offset %>
    <%= hidden_field :date_time, :year %>
    <%= hidden_field :date_time, :day %>
    <%= hidden_field :date_time, :month %>
    <%= f.submit "Set as Current Location", class: "btn btn-sand js-submit" %>
  <% end %>
<% end %>

app/views/locations/create.html.erb
<h1>Locations#create</h1>
<p>Find me in app/views/locations/create.html.erb</p>

app/views/locations/destroy.js.erb
$('#location_<%= @location.id %>').remove();

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>

app/views/users/_has_location.html.erb
<div class="container-fluid knobs-container">
  <div class="col-md-6 col-sm-6 col-lg-3 col-xs-12">
    <div class="panel panel-primary js-panel">
      <div class="panel-heading">
        <b>Elevation Angle</b>
        <i class="glyphicon glyphicon-chevron-up"></i>
      </div>
      <div class="panel-body text-center collapse in">
        <input class="js-knob-elevation-angle" data-width="200" data-displayPrevious=true data-fgColor="#337ab7" data-skin="tron" data-thickness=".2" data-min="-180" data-max="180" data-angleOffset="180" readonly />
      </div>
       <div class="panel-footer" style="color:#337ab7">Vitamin D can be produced when the elevation angle above is <b>50°</b>.</div>
    </div>
  </div>
  <div class="col-md-6 col-sm-6 col-lg-3 col-xs-12">
    <div class="panel panel-primary js-panel">
      <div class="panel-heading">
        <b>Sunbathing time left</b>
        <i class="glyphicon glyphicon-chevron-up"></i>
      </div>
      <div class="panel-body text-center collapse in">
        <input class="js-knob-sunbathing-time" data-width="200" data-displayPrevious=true data-fgColor="#337ab7" data-skin="tron" data-thickness=".2" data-max="360" readonly disabled value="75"/>
      </div>
       <div class="panel-footer" style="color:#337ab7">The amount of time left until the elevation angle will be below <b>50°</b>.</div>
    </div>
  </div>  
  <div class="col-md-6  col-sm-6 col-lg-3 col-xs-12">
    <div class="panel panel-primary js-panel">
      <div class="panel-heading">
        <b>Sunbathing time begins at</b>
        <i class="glyphicon glyphicon-chevron-up"></i>
      </div>
      <div class="panel-body text-center collapse in">
        <input class="js-knob-sunbathing-start" data-width="200" data-displayPrevious=true data-fgColor="#337ab7" data-skin="tron" data-thickness=".2" data-max="86400" readonly disabled value="75"/>
      </div>
       <div class="panel-footer" style="color:#337ab7">From this moment the elevation angle is above <b>50°</b> and your body can produce Vitamin D. </div>
    </div>
  </div>
  <div class="col-md-6 col-sm-6 col-lg-3 col-xs-12">
    <div class="panel panel-primary js-panel">
      <div class="panel-heading">
        <b>Sunbathing time ends at</b>
        <i class="glyphicon glyphicon-chevron-up"></i>
      </div>
      <div class="panel-body text-center collapse in">
        <input class="js-knob-sunbathing-end" data-width="200" data-displayPrevious=true data-fgColor="#337ab7" data-skin="tron" data-thickness=".2" data-max="86400" readonly disabled value="75"/>
      </div>
       <div class="panel-footer" style="color:#337ab7">After this moment the elevation angle is below <b>50°</b> and your body can't produce Vitamin D.</div>
    </div>
  </div>
  <!-- <div class="panel panel-primary">
    <div class="panel-heading">Current Time</div>
    <div class="panel-body text-center">
      <input class="js-knob-current-time" data-width="200" data-displayPrevious=true data-fgColor="#337ab7" data-skin="tron" data-thickness=".2" data-max="86400" readonly disabled value="75"/>
    </div>
     <div class="panel-footer" style="color:#337ab7">The current time on your device.</div>
  </div> -->
</div>
<div class="container-fluid js-location-form has-location">
  <span class="btn btn-success">
    <i class="glyphicon glyphicon-map-marker"></i>
    <b><%= "#{current_user.current_location.city}, #{current_user.current_location.country}" %></b>
  </span>
  <%= form_for( location, url: user_locations_post_update_path(current_user), remote: true ) do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :longitude %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :current_location %>
    <%= hidden_field :date_time, :offset %>
    <%= hidden_field :date_time, :year %>
    <%= hidden_field :date_time, :day %>
    <%= hidden_field :date_time, :month %>
    <%= f.submit "Update Location", class: "btn btn-sand js-submit", style: "margin-bottom: 20px" %>
  <% end %>
</div>
<div class="container-fluid chart-container col-md-12 col-lg-12 col-xs-12 col-sm-12">
  <div id="chart_div" data-current-user="<%= current_user.id %>" style="height: 100%">
  </div>
  <%= render partial: 'spinner' %>
</div>

app/views/users/_location_form.html.erb
  <span class="btn btn-success">
    <i class="glyphicon glyphicon-map-marker"></i>
    <b><%= "#{current_user.current_location.city}, #{current_user.current_location.country}" %></b>
  </span>
  <%= form_for( @location, url: user_locations_post_update_path(current_user), remote: true ) do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :longitude %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :current_location %>
    <%= hidden_field :date_time, :offset %>
    <%= hidden_field :date_time, :year %>
    <%= hidden_field :date_time, :day %>
    <%= hidden_field :date_time, :month %>
    <%= f.submit "Update Location", class: "btn btn-default btn-sand js-submit" %>
  <% end %>

app/views/users/_no_location.html.erb
<div class="container js-location-form no-location">
  <%= form_for( location, url: user_locations_path(current_user) ) do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :longitude %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :current_location, value: true %>
    <%= hidden_field :date_time, :offset %>
    <%= hidden_field :date_time, :year %>
    <%= hidden_field :date_time, :day %>
    <%= hidden_field :date_time, :month %>
    <%= f.submit class: "js-submit" %>
  <% end %>
</div>
<div class="container col-md-12 col-lg-12 col-xs-12" style="height: 240px">
  <div id="chart_div" style="height: 100%">
  </div>
  <%= render partial: 'spinner' %>
</div>